set @dayOfWeek = 'Tuesday';
set @startDate = (SELECT SeasonStartDate FROM SeasonDates);
set @endDate = (SELECT SeasonEndDate FROM SeasonDates);

set @i = -1;
SELECT
		DATE(ADDDATE(@startDate, INTERVAL @i:=@i + 1 DAY)) AS Tuesday
FROM SeasonDates,
    (SELECT
        a.a
    FROM
        (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS a
    CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS b
    CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS c) a
HAVING @i < DATEDIFF(@endDate, @startDate)
    AND DAYNAME(Tuesday +1) = @dayOfWeek;